# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/RAgrb"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Raniaghribi"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:rania123.gribi123@gmail.com"

[social.params]
icon = "brand-email.svg"

# Redirect rule for the email link
[[redirects]]
  from = "/contact"  # The URL path you want to redirect from
  to = "mailto:rania123.gribi123@gmail.com"  # The target email address
  status = 302  # Use 302 for temporary redirects or 301 for permanent redirects


