version: '3'

services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "1313:1313"
    volumes:
      - .:/app
    command: ["hugo", "server", "--bind=0.0.0.0", "--port=1313", "--appendPort=false", "--disableFastRender"]
